<?php

declare(strict_types=1);

namespace HiEvents\Console\Commands\Monno;

/**
 * The curated content the monno website is seeded with.
 *
 * The site used to carry a hand-written demo catalogue in its own repo; this is
 * the same idea, but real rows in the platform database. One event per category
 * so every category tile fills, across eight organizer accounts and a handful of
 * cities that have photography on the site.
 */
final class MonnoSeedContent
{
    /**
     * @return array<string, array{name:string, city:string, country:string, timezone:string, currency:string, colour:string, initials:string, bio:string}>
     */
    public static function organizers(): array
    {
        return [
            'northlight' => [
                'name' => 'Northlight Studio',
                'city' => 'New York',
                'country' => 'US',
                'timezone' => 'America/New_York',
                'currency' => 'USD',
                'colour' => '#D2601A',
                'initials' => 'NS',
                'bio' => 'A small production studio putting on open-air music, film and art nights across the city.',
            ],
            'fieldnotes' => [
                'name' => 'Field Notes Collective',
                'city' => 'London',
                'country' => 'GB',
                'timezone' => 'Europe/London',
                'currency' => 'USD',
                'colour' => '#3B6E8F',
                'initials' => 'FN',
                'bio' => 'A reading and conversation series for people who like their ideas out loud.',
            ],
            'commonground' => [
                'name' => 'Common Ground Events',
                'city' => 'Singapore',
                'country' => 'SG',
                'timezone' => 'Asia/Singapore',
                'currency' => 'USD',
                'colour' => '#2E7D5B',
                'initials' => 'CG',
                'bio' => 'Food, craft and neighbourhood gatherings built around long tables and slow afternoons.',
            ],
            'harbourrun' => [
                'name' => 'Harbour Running Co.',
                'city' => 'Sydney',
                'country' => 'AU',
                'timezone' => 'Australia/Sydney',
                'currency' => 'USD',
                'colour' => '#C24B3A',
                'initials' => 'HR',
                'bio' => 'Weekly social runs and one big race a year. All paces, no egos.',
            ],
            'stillroom' => [
                'name' => 'Stillroom',
                'city' => 'Dublin',
                'country' => 'IE',
                'timezone' => 'Europe/Dublin',
                'currency' => 'USD',
                'colour' => '#5945B1',
                'initials' => 'SR',
                'bio' => 'A late-night room for club music, comedy and the odd film print.',
            ],
            'meridian' => [
                'name' => 'Meridian Labs',
                'city' => 'Berlin',
                'country' => 'DE',
                'timezone' => 'Europe/Berlin',
                'currency' => 'USD',
                'colour' => '#1478C9',
                'initials' => 'ML',
                'bio' => 'A workshop and hack space for people who build things and explain them well.',
            ],
            'atelierlune' => [
                'name' => 'Atelier Lune',
                'city' => 'Paris',
                'country' => 'FR',
                'timezone' => 'Europe/Paris',
                'currency' => 'USD',
                'colour' => '#B0479A',
                'initials' => 'AL',
                'bio' => 'An art and craft studio running open tables, exhibitions and family afternoons.',
            ],
            'wanderline' => [
                'name' => 'Wanderline',
                'city' => 'Lisbon',
                'country' => 'PT',
                'timezone' => 'Europe/Lisbon',
                'currency' => 'USD',
                'colour' => '#C98A14',
                'initials' => 'WL',
                'bio' => 'Walking tours, city festivals and long days outdoors along the coast.',
            ],
        ];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public static function events(): array
    {
        return [
            [
                'organizer' => 'northlight', 'category' => 'MUSIC',
                'city' => 'New York', 'country' => 'US', 'region' => 'NY', 'timezone' => 'America/New_York',
                'venue' => 'Pier 17 Rooftop', 'address' => '89 South Street', 'zip' => '10038',
                'lat' => 40.7061, 'lng' => -74.0030,
                'title' => 'Night Sessions: Open-Air Music',
                'tagline' => 'Three live acts, one long set, and the skyline behind the stage.',
                'blurb' => 'Night Sessions returns for one open-air night on the water. Three acts, no support slots, no filler — the bill runs straight through from a slow first set to a full-band close.',
                'price' => 38, 'capacity' => 900, 'dayOffset' => 21, 'hour' => 19, 'minute' => 30, 'durationHours' => 4,
                'featured' => true, 'image' => 'hero-festival.jpg',
            ],
            [
                'organizer' => 'stillroom', 'category' => 'NIGHTLIFE',
                'city' => 'Dublin', 'country' => 'IE', 'region' => 'Co. Dublin', 'timezone' => 'Europe/Dublin',
                'venue' => 'The Coal Yard', 'address' => '14 Newmarket Square', 'zip' => 'D08 XY42',
                'lat' => 53.3369, 'lng' => -6.2793,
                'title' => 'SUBTERRA 004 — Nite Kernel, Ánima, Basil Wren',
                'tagline' => 'One room, four hours, and a soundsystem that does not negotiate.',
                'blurb' => 'The fourth SUBTERRA takes over the Coal Yard for a single-room night: Nite Kernel closing, Ánima after midnight, Basil Wren warming it up on the small stack.',
                'price' => 16, 'capacity' => 320, 'dayOffset' => 12, 'hour' => 23, 'minute' => 0, 'durationHours' => 6,
                'featured' => true, 'image' => 'event-nightlife.jpg',
            ],
            [
                'organizer' => 'fieldnotes', 'category' => 'EDUCATION',
                'city' => 'London', 'country' => 'GB', 'region' => 'Greater London', 'timezone' => 'Europe/London',
                'venue' => 'The Reading Room', 'address' => '5 Redchurch Street', 'zip' => 'E2 7DJ',
                'lat' => 51.5245, 'lng' => -0.0746,
                'title' => 'Field Notes: How We Learn Now',
                'tagline' => 'Three short talks and one long argument about learning in public.',
                'blurb' => 'An evening of short talks on how people actually pick things up — apprenticeships, group study and the strange durability of a well-kept notebook. Questions run until the room runs out.',
                'price' => 12, 'capacity' => 120, 'dayOffset' => 9, 'hour' => 18, 'minute' => 30, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-bookclub.jpg',
            ],
            [
                'organizer' => 'commonground', 'category' => 'FOOD_DRINK',
                'city' => 'Singapore', 'country' => 'SG', 'region' => '', 'timezone' => 'Asia/Singapore',
                'venue' => 'Long Table Hall', 'address' => '12 Tiong Bahru Road', 'zip' => '168730',
                'lat' => 1.2845, 'lng' => 103.8290,
                'title' => 'Long Table: A Sunday Lunch',
                'tagline' => 'One table, forty seats, and a kitchen doing whatever the market had this morning.',
                'blurb' => 'A slow Sunday lunch where you sit next to someone you have not met. The kitchen cooks from the morning market, the table seats forty, and nobody is expected to leave before four.',
                'price' => 42, 'capacity' => 40, 'dayOffset' => 7, 'hour' => 12, 'minute' => 30, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-market.jpg',
            ],
            [
                'organizer' => 'harbourrun', 'category' => 'FITNESS',
                'city' => 'Sydney', 'country' => 'AU', 'region' => 'NSW', 'timezone' => 'Australia/Sydney',
                'venue' => 'Mrs Macquarie\u2019s Point', 'address' => '1 Mrs Macquarie\u2019s Road', 'zip' => '2000',
                'lat' => -33.8590, 'lng' => 151.2150,
                'title' => 'Harbour Half Marathon',
                'tagline' => '21.1 km along the water, then breakfast.',
                'blurb' => 'The big one. A flat, fast half along the harbour with four water points, pacers from 1:30 to 2:30, and a long breakfast afterwards that is half the reason people enter.',
                'price' => 55, 'capacity' => 2500, 'dayOffset' => 45, 'hour' => 6, 'minute' => 30, 'durationHours' => 4,
                'featured' => true, 'image' => 'event-marathon.jpg',
            ],
            [
                'organizer' => 'stillroom', 'category' => 'COMEDY',
                'city' => 'Dublin', 'country' => 'IE', 'region' => 'Co. Dublin', 'timezone' => 'Europe/Dublin',
                'venue' => 'The Back Room', 'address' => '22 Wexford Street', 'zip' => 'D02 XY45',
                'lat' => 53.3360, 'lng' => -6.2640,
                'title' => 'New Material Night',
                'tagline' => 'Six comics, half-finished jokes, and nothing you have heard before.',
                'blurb' => 'A work-in-progress night for comics trying things out. Some of it will not land, which is the point — tickets are cheap and the room is small enough that you are part of it.',
                'price' => 8, 'capacity' => 90, 'dayOffset' => 4, 'hour' => 20, 'minute' => 0, 'durationHours' => 2,
                'featured' => false, 'image' => 'event-comedy.jpg',
            ],
            [
                'organizer' => 'fieldnotes', 'category' => 'THEATER',
                'city' => 'London', 'country' => 'GB', 'region' => 'Greater London', 'timezone' => 'Europe/London',
                'venue' => 'The Old Workshop', 'address' => '18 Ashwin Street', 'zip' => 'E8 3DL',
                'lat' => 51.5470, 'lng' => -0.0750,
                'title' => 'A Small Hour — Three One-Act Plays',
                'tagline' => 'Three new plays, one set, no interval.',
                'blurb' => 'Three one-act plays by writers from the collective, staged on a single set with no interval. Around eighty minutes in total, then the bar downstairs stays open.',
                'price' => 18, 'capacity' => 110, 'dayOffset' => 17, 'hour' => 19, 'minute' => 30, 'durationHours' => 2,
                'featured' => false, 'image' => 'event-theater.jpg',
            ],
            [
                'organizer' => 'northlight', 'category' => 'FILM',
                'city' => 'New York', 'country' => 'US', 'region' => 'NY', 'timezone' => 'America/New_York',
                'venue' => 'The Yard Screen', 'address' => '45 Wythe Avenue', 'zip' => '11249',
                'lat' => 40.7220, 'lng' => -73.9580,
                'title' => 'Open-Air Screen: The Long Take',
                'tagline' => 'One film, one unbroken take, under the bridge.',
                'blurb' => 'A single film chosen for its long takes, projected onto a wall in the yard with the bridge overhead. Bring a blanket; the deck chairs go first.',
                'price' => 14, 'capacity' => 220, 'dayOffset' => 11, 'hour' => 20, 'minute' => 15, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-film.jpg',
            ],
            [
                'organizer' => 'atelierlune', 'category' => 'DANCE',
                'city' => 'Paris', 'country' => 'FR', 'region' => '\u00cele-de-France', 'timezone' => 'Europe/Paris',
                'venue' => 'Studio Rue Verte', 'address' => '7 Rue Verte', 'zip' => '75011',
                'lat' => 48.8560, 'lng' => 2.3760,
                'title' => 'Open Floor: Contemporary Dance',
                'tagline' => 'Two hours of movement, live percussion and no steps to learn.',
                'blurb' => 'A guided open floor — an hour of improvisation led by a dancer from the studio, then an hour of live percussion where the room takes over. No experience needed, bare feet or socks.',
                'price' => 15, 'capacity' => 60, 'dayOffset' => 14, 'hour' => 19, 'minute' => 0, 'durationHours' => 2,
                'featured' => false, 'image' => 'event-dance.jpg',
            ],
            [
                'organizer' => 'atelierlune', 'category' => 'ART',
                'city' => 'Paris', 'country' => 'FR', 'region' => '\u00cele-de-France', 'timezone' => 'Europe/Paris',
                'venue' => 'Galerie Miroir', 'address' => '30 Rue de Turenne', 'zip' => '75003',
                'lat' => 48.8575, 'lng' => 2.3645,
                'title' => 'Twelve Printmakers — Opening Night',
                'tagline' => 'Twelve printmakers, one wall, and the artists pouring the wine.',
                'blurb' => 'The opening of a group show of screenprints and etchings by twelve artists the studio has worked with this year. The artists are in the room, the editions are on the table, and the show runs three weeks.',
                'price' => 0, 'capacity' => 200, 'dayOffset' => 6, 'hour' => 18, 'minute' => 0, 'durationHours' => 4,
                'featured' => true, 'image' => 'event-gallery.jpg',
            ],
            [
                'organizer' => 'commonground', 'category' => 'SOCIAL',
                'city' => 'Singapore', 'country' => 'SG', 'region' => '', 'timezone' => 'Asia/Singapore',
                'venue' => 'The Kopi Room', 'address' => '4 Everton Park', 'zip' => '080004',
                'lat' => 1.2770, 'lng' => 103.8400,
                'title' => 'Neighbours: A Coffee Morning',
                'tagline' => 'Coffee, toast, and the people who live on your street.',
                'blurb' => 'A standing monthly coffee morning for the neighbourhood. Nothing is organised beyond the coffee and the toast — come for ten minutes or stay until the pots run out.',
                'price' => 0, 'capacity' => 70, 'dayOffset' => 5, 'hour' => 9, 'minute' => 30, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-coffee.jpg',
            ],
            [
                'organizer' => 'atelierlune', 'category' => 'FAMILY',
                'city' => 'Paris', 'country' => 'FR', 'region' => '\u00cele-de-France', 'timezone' => 'Europe/Paris',
                'venue' => 'Atelier Lune', 'address' => '12 Rue des Lilas', 'zip' => '75019',
                'lat' => 48.8770, 'lng' => 2.3920,
                'title' => 'Family Craft Afternoon',
                'tagline' => 'Paint, clay and glue, with the mess left at the door.',
                'blurb' => 'An open afternoon for families: three tables, one for paint, one for clay and one for whatever the older children are building. Everything is washable and the floor is the floor.',
                'price' => 6, 'capacity' => 80, 'dayOffset' => 10, 'hour' => 14, 'minute' => 0, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-family-craft.jpg',
            ],
            [
                'organizer' => 'fieldnotes', 'category' => 'HOBBIES',
                'city' => 'London', 'country' => 'GB', 'region' => 'Greater London', 'timezone' => 'Europe/London',
                'venue' => 'The Snug', 'address' => '9 Columbia Road', 'zip' => 'E2 7RG',
                'lat' => 51.5285, 'lng' => -0.0690,
                'title' => 'Board Games, Badly Explained',
                'tagline' => 'Bring a game, teach it in five minutes, win nothing.',
                'blurb' => 'A monthly tabletop night where everyone brings one game and has to teach it in five minutes. There are no prizes, the rules are frequently wrong, and it is the best-attended thing the collective runs.',
                'price' => 5, 'capacity' => 60, 'dayOffset' => 13, 'hour' => 18, 'minute' => 30, 'durationHours' => 4,
                'featured' => false, 'image' => 'event-board-games.jpg',
            ],
            [
                'organizer' => 'harbourrun', 'category' => 'OUTDOORS',
                'city' => 'Sydney', 'country' => 'AU', 'region' => 'NSW', 'timezone' => 'Australia/Sydney',
                'venue' => 'Bondi to Coogee Path', 'address' => 'Notts Avenue', 'zip' => '2026',
                'lat' => -33.8910, 'lng' => 151.2740,
                'title' => 'Coastal Walk: Sunrise to Breakfast',
                'tagline' => 'Six kilometres of coast path, starting before the light.',
                'blurb' => 'A guided walk along the coastal path leaving before sunrise, finishing in a cafe that opens early for the group. Easy pace, a few stairs, and the best light of the day.',
                'price' => 0, 'capacity' => 40, 'dayOffset' => 8, 'hour' => 5, 'minute' => 45, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-seedlings.jpg',
            ],
            [
                'organizer' => 'harbourrun', 'category' => 'WELLNESS',
                'city' => 'Sydney', 'country' => 'AU', 'region' => 'NSW', 'timezone' => 'Australia/Sydney',
                'venue' => 'The Light Room', 'address' => '3 Enmore Road', 'zip' => '2042',
                'lat' => -33.8990, 'lng' => 151.1750,
                'title' => 'Morning Reset: Breath and Movement',
                'tagline' => 'One hour, one mat, before the rest of the day gets a say.',
                'blurb' => 'A slow morning session of breathwork and easy movement, designed for people who sit at desks. Mats are provided; the hour ends before most offices open.',
                'price' => 18, 'capacity' => 30, 'dayOffset' => 3, 'hour' => 7, 'minute' => 0, 'durationHours' => 1,
                'featured' => false, 'image' => 'event-yoga.jpg',
            ],
            [
                'organizer' => 'atelierlune', 'category' => 'SPIRITUALITY',
                'city' => 'Paris', 'country' => 'FR', 'region' => '\u00cele-de-France', 'timezone' => 'Europe/Paris',
                'venue' => 'Chapelle des Arts', 'address' => '2 Rue de la Roquette', 'zip' => '75011',
                'lat' => 48.8550, 'lng' => 2.3730,
                'title' => 'Evening of Stillness',
                'tagline' => 'An hour of quiet, with candles and no instruction.',
                'blurb' => 'An hour of shared quiet in a small chapel — candles, a little music at the start, and no instruction after that. Come and go in silence; the doors are open for the full hour.',
                'price' => 0, 'capacity' => 90, 'dayOffset' => 16, 'hour' => 20, 'minute' => 0, 'durationHours' => 1,
                'featured' => false, 'image' => 'event-spirituality.jpg',
            ],
            [
                'organizer' => 'commonground', 'category' => 'CHARITY',
                'city' => 'Singapore', 'country' => 'SG', 'region' => '', 'timezone' => 'Asia/Singapore',
                'venue' => 'The Warehouse', 'address' => '50 Kallang Avenue', 'zip' => '339511',
                'lat' => 1.3120, 'lng' => 103.8630,
                'title' => 'Give and Take: A Charity Sale',
                'tagline' => 'Everything is donated; everything is five dollars.',
                'blurb' => 'A warehouse sale where everything has been donated and everything costs the same. Proceeds go to the food bank two streets over, and whatever is left at the end goes to them too.',
                'price' => 5, 'capacity' => 400, 'dayOffset' => 19, 'hour' => 10, 'minute' => 0, 'durationHours' => 6,
                'featured' => false, 'image' => 'event-charity.jpg',
            ],
            [
                'organizer' => 'fieldnotes', 'category' => 'BUSINESS',
                'city' => 'London', 'country' => 'GB', 'region' => 'Greater London', 'timezone' => 'Europe/London',
                'venue' => 'The Exchange', 'address' => '1 Finsbury Avenue', 'zip' => 'EC2M 2PF',
                'lat' => 51.5190, 'lng' => -0.0860,
                'title' => 'Small Companies, Honest Numbers',
                'tagline' => 'Four founders on what the spreadsheet actually looked like.',
                'blurb' => 'Four founders of small companies walk through a year of real numbers — margins, mistakes and the month it nearly did not work. No pitch decks, no growth theatre.',
                'price' => 22, 'capacity' => 150, 'dayOffset' => 24, 'hour' => 18, 'minute' => 0, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-conference.jpg',
            ],
            [
                'organizer' => 'meridian', 'category' => 'TECH',
                'city' => 'Berlin', 'country' => 'DE', 'region' => 'Berlin', 'timezone' => 'Europe/Berlin',
                'venue' => 'Meridian Hall', 'address' => '20 Oranienstraße', 'zip' => '10999',
                'lat' => 52.5030, 'lng' => 13.4230,
                'title' => 'Local First: A Build Night',
                'tagline' => 'Six teams, one evening, software that works offline.',
                'blurb' => 'A build night for people interested in software that works without a server. Six teams demo what they made since the last one, and the room argues about sync for an hour afterwards.',
                'price' => 10, 'capacity' => 140, 'dayOffset' => 15, 'hour' => 18, 'minute' => 30, 'durationHours' => 4,
                'featured' => false, 'image' => 'event-hackathon.jpg',
            ],
            [
                'organizer' => 'meridian', 'category' => 'WORKSHOP',
                'city' => 'Berlin', 'country' => 'DE', 'region' => 'Berlin', 'timezone' => 'Europe/Berlin',
                'venue' => 'Werkstatt 4', 'address' => '8 Ritterstraße', 'zip' => '10969',
                'lat' => 52.5020, 'lng' => 13.4100,
                'title' => 'Build a Radio in a Day',
                'tagline' => 'One day, one receiver, and you take it home.',
                'blurb' => 'A full-day workshop building a simple receiver from a kit. Tools, parts and lunch provided; by six o’clock you will have heard something you built yourself.',
                'price' => 65, 'capacity' => 20, 'dayOffset' => 28, 'hour' => 10, 'minute' => 0, 'durationHours' => 8,
                'featured' => false, 'image' => 'event-workshop.jpg',
            ],
            [
                'organizer' => 'wanderline', 'category' => 'TOURS',
                'city' => 'Lisbon', 'country' => 'PT', 'region' => '', 'timezone' => 'Europe/Lisbon',
                'venue' => 'Praça do Comércio', 'address' => 'Praça do Comércio', 'zip' => '1100-148',
                'lat' => 38.7075, 'lng' => -9.1364,
                'title' => 'The Hills and the Water: A Walking Tour',
                'tagline' => 'Three hours uphill, with the good viewpoints and no souvenir shops.',
                'blurb' => 'A walking tour of the city’s seven hills that skips the obvious streets. Three hours, a lot of steps, two viewpoints and a stop for coffee that the guide pays for out of the ticket.',
                'price' => 25, 'capacity' => 18, 'dayOffset' => 6, 'hour' => 10, 'minute' => 0, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-tours.jpg',
            ],
            [
                'organizer' => 'wanderline', 'category' => 'FESTIVAL',
                'city' => 'Lisbon', 'country' => 'PT', 'region' => '', 'timezone' => 'Europe/Lisbon',
                'venue' => 'Jardim da Estrela', 'address' => 'Praça da Estrela', 'zip' => '1200-667',
                'lat' => 38.7140, 'lng' => -9.1600,
                'title' => 'Estrela Summer Festival',
                'tagline' => 'Two days in the garden: music, food and a lot of shade.',
                'blurb' => 'Two days in the city’s best garden with a small stage, a food row and more shade than most festivals manage. Family-friendly until eight, then the music turns up.',
                'price' => 30, 'capacity' => 1500, 'dayOffset' => 40, 'hour' => 14, 'minute' => 0, 'durationHours' => 8,
                'featured' => true, 'image' => 'event-festival.jpg',
            ],
            [
                'organizer' => 'commonground', 'category' => 'SEASONAL',
                'city' => 'Singapore', 'country' => 'SG', 'region' => '', 'timezone' => 'Asia/Singapore',
                'venue' => 'The Covered Street', 'address' => '30 Pagoda Street', 'zip' => '059189',
                'lat' => 1.2840, 'lng' => 103.8440,
                'title' => 'Night Market: End of Season',
                'tagline' => 'One street, thirty stalls, and the last of the season.',
                'blurb' => 'The last night market of the season takes over a single covered street with thirty stalls, lanterns and a stage at the far end. Bring cash for the small stalls.',
                'price' => 0, 'capacity' => 800, 'dayOffset' => 18, 'hour' => 17, 'minute' => 0, 'durationHours' => 6,
                'featured' => false, 'image' => 'event-christmas-market.jpg',
            ],
            [
                'organizer' => 'meridian', 'category' => 'OTHER',
                'city' => 'Berlin', 'country' => 'DE', 'region' => 'Berlin', 'timezone' => 'Europe/Berlin',
                'venue' => 'The Long Hall', 'address' => '15 Köpenicker Straße', 'zip' => '10997',
                'lat' => 52.5000, 'lng' => 13.4320,
                'title' => 'The Repair Café',
                'tagline' => 'Bring something broken; leave with it working.',
                'blurb' => 'A monthly repair café with volunteers who fix bikes, lamps, radios and the occasional toaster. Bring the thing and the part if you have it; stay and watch if you do not.',
                'price' => 0, 'capacity' => 120, 'dayOffset' => 20, 'hour' => 11, 'minute' => 0, 'durationHours' => 4,
                'featured' => false, 'image' => 'event-making.jpg',
            ],
            // Past events — the organizer rooms' archive tab.
            [
                'organizer' => 'northlight', 'category' => 'MUSIC',
                'city' => 'New York', 'country' => 'US', 'region' => 'NY', 'timezone' => 'America/New_York',
                'venue' => 'Pier 17 Rooftop', 'address' => '89 South Street', 'zip' => '10038',
                'lat' => 40.7061, 'lng' => -74.0030,
                'title' => 'Night Sessions: Spring Edition',
                'tagline' => 'The first open-air night of the year, sold out in a week.',
                'blurb' => 'The spring edition of Night Sessions, with two acts and a cold wind off the water that nobody minded. Archived here for the record.',
                'price' => 34, 'capacity' => 900, 'dayOffset' => -18, 'hour' => 19, 'minute' => 30, 'durationHours' => 4,
                'featured' => false, 'image' => 'hero-festival.jpg',
            ],
            [
                'organizer' => 'commonground', 'category' => 'FOOD_DRINK',
                'city' => 'Singapore', 'country' => 'SG', 'region' => '', 'timezone' => 'Asia/Singapore',
                'venue' => 'Long Table Hall', 'address' => '12 Tiong Bahru Road', 'zip' => '168730',
                'lat' => 1.2845, 'lng' => 103.8290,
                'title' => 'Long Table: The First Lunch',
                'tagline' => 'Where the long table started.',
                'blurb' => 'The first Long Table lunch, back when the kitchen was borrowed and the table was two tables pushed together.',
                'price' => 38, 'capacity' => 40, 'dayOffset' => -25, 'hour' => 12, 'minute' => 30, 'durationHours' => 3,
                'featured' => false, 'image' => 'event-market.jpg',
            ],
            [
                'organizer' => 'meridian', 'category' => 'TECH',
                'city' => 'Berlin', 'country' => 'DE', 'region' => 'Berlin', 'timezone' => 'Europe/Berlin',
                'venue' => 'Meridian Hall', 'address' => '20 Oranienstraße', 'zip' => '10999',
                'lat' => 52.5030, 'lng' => 13.4230,
                'title' => 'Local First: Edition One',
                'tagline' => 'The build night that started the series.',
                'blurb' => 'The first Local First build night, with four teams and a projector that overheated twice.',
                'price' => 10, 'capacity' => 140, 'dayOffset' => -11, 'hour' => 18, 'minute' => 30, 'durationHours' => 4,
                'featured' => false, 'image' => 'event-hackathon.jpg',
            ],
        ];
    }
}
